// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5wjJUuDcG_bMDhpEZcDy2PfrhPSFiIEI',
    appId: '1:70936835012:web:cc03f833516955304baa91',
    messagingSenderId: '70936835012',
    projectId: 'gyaanplant-da98d',
    authDomain: 'gyaanplant-da98d.firebaseapp.com',
    storageBucket: 'gyaanplant-da98d.firebasestorage.app',
    measurementId: 'G-1G2BNE3F5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeIVHs2O55f4mR-O1PeQOgzgu71jhOTNY',
    appId: '1:70936835012:android:b2f0ab7492b8497e4baa91',
    messagingSenderId: '70936835012',
    projectId: 'gyaanplant-da98d',
    storageBucket: 'gyaanplant-da98d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX4XJcdsmlBEpTE-iL1PQnZeVymx9Eihw',
    appId: '1:70936835012:ios:485cbfa9e099851f4baa91',
    messagingSenderId: '70936835012',
    projectId: 'gyaanplant-da98d',
    storageBucket: 'gyaanplant-da98d.firebasestorage.app',
    iosBundleId: 'com.example.gyaanplant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX4XJcdsmlBEpTE-iL1PQnZeVymx9Eihw',
    appId: '1:70936835012:ios:485cbfa9e099851f4baa91',
    messagingSenderId: '70936835012',
    projectId: 'gyaanplant-da98d',
    storageBucket: 'gyaanplant-da98d.firebasestorage.app',
    iosBundleId: 'com.example.gyaanplant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5wjJUuDcG_bMDhpEZcDy2PfrhPSFiIEI',
    appId: '1:70936835012:web:a422029f0e99f1ef4baa91',
    messagingSenderId: '70936835012',
    projectId: 'gyaanplant-da98d',
    authDomain: 'gyaanplant-da98d.firebaseapp.com',
    storageBucket: 'gyaanplant-da98d.firebasestorage.app',
    measurementId: 'G-GT51Y86ZKS',
  );
}
